on:
  workflow_dispatch:
  push:
  
jobs:
  hosted-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x /home/runner/work/actions-load-test/actions-load-test/src/test-script.sh
          ./home/runner/work/actions-load-test/actions-load-test/src/test-script.sh
    
  selfhosted-runner:
    runs-on: self-hosted
    steps:
      - run: |
          chmod +x /home/runner/work/actions-load-test/actions-load-test/src/test-script.sh
          ./home/runner/work/actions-load-test/actions-load-test/src/test-script.sh
          
