on:
  workflow_dispatch:
  
jobs:
  #hosted-runner:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: execute test
  #      run: |
  #        chmod +x /home/runner/work/actions-load-test/actions-load-test/sr/test-script.sh
  #        ./sr/test-script.sh
    
  selfhosted-runner:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: execute test
        run: |
          chmod +x /home/runner/_work/actions-load-test/actions-load-test/sr/test-script.sh
          ./sr/test-script.sh
          
