on:
  workflow_dispatch:
  push:
  
jobs:
  hosted-runner:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - run: sleep 10s
    
  selfhosted-runner:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Hello world"
          sleep 10s
          echo "Wake up!"
          
      - run: |
          for i in ${1-120}
          do
            echo "$i"
            sleep 1s
          done
