on:
  workflow_dispatch:
  push:
  
jobs:
  hosted-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: execute test
        run: |
          chmod +x /sr/test-script.sh
          ./sr/test-script.sh
    
  selfhosted-runner:
    runs-on: self-hosted
    steps:
      - name: execute test
        run: |
          chmod +x /sr/test-script.sh
          ./sr/test-script.sh
          
